### ISSUE TITLE
Repo ranger merged immediately without waiting for passing events

### ISSUE THREAD

**Issue by moltar** [reporanger/feedback#1]
I created a PR using a CLI:

```sh
 hub pull-request -p -l "merge when passing"
```

<img width="919" alt="image" src="https://user-images.githubusercontent.com/491247/85531817-4d084480-b639-11ea-87fd-b8e98ebc5d7e.png">

The bot merged my PR immediately, 2 seconds after the PR was created.

I think this might be a race condition, as GitHub Actions did not start yet, and bot thought that everything was done.

Maybe the bot needs to detect checks that haven't started yet, or allow for some grace period before merging?

**Comment by mfix22** [comment]
@moltar sorry to hear this happened to you, and thank you for reporting it. I had not seen this issue in the past. 

It does seem to me to be a race condition with GitHub actions, so I am going to add a delay to our response, and push up the fix tonight. 

Give it another try whenever you have a chance, and let me know if it works. Might need to tweak our delay some more.

**Comment by mfix22** [comment]
Great use of `hub`, by the way!

**Comment by moltar** [comment]
Thank you 🙏 

Will try again soon!

**Comment by mfix22** [comment]
Thanks @moltar! 🙏

**Comment by moltar** [comment]
Seems to work fine now! :)

Evidence: https://github.com/ScaleLeap/logger/pull/75

**Comment by mfix22** [comment]
@moltar thank you so much for checking! ❤️
