### ISSUE TITLE
RR not picking up a repo

### ISSUE THREAD

**Issue by moltar** [reporanger/feedback#2]
For some odd reason RR is not seeing one of the [repos](https://github.com/ScaleLeap/puppeteer) (private), however it is granted all repo access.

By not seeing, I mean not reacting to label `merge when passing`.

Any idea?

Thanks!

**Comment by mfix22** [comment]
@moltar Repo Ranger is only available for free for public repos, as you can see from our Pricing section here: https://reporanger.com/

That said, I can whitelist your username in the meantime.

**Comment by moltar** [comment]
Oh, was it always the case? I was pretty sure it did work on private repos at some point.

How much is the service, btw? Will it be a GitHub App, or an enterprise solution / pricing?

If you can whitelist for now, that would be amazing :)

Thanks.

**Comment by mfix22** [comment]
@moltar yes, that has always been the case!

It is actually already a GitHub app on the marketplace (http://github.com/marketplace/ranger), but GitHub has not accepted our App for paid pricing. 

The "Maker" plan, which I assume will roughly suit your needs, will be ~$10-30/month — does that seem fair to you? 

In the meantime, I have whitelisted your username, as well as @scaleleap.

**Comment by moltar** [comment]
I think $5 is fair. I would not pay $10 :) But my volume is pretty low.

At $10, I'd probably write a Lambda function to do merging, because that is the only feature I am interested in at the moment.

**Comment by moltar** [comment]
> In the meantime, I have whitelisted your username, as well as @ScaleLeap.

Awesome, thanks! :)

**Comment by mfix22** [comment]
> At $10, I'd probably write a Lambda function to do merging, because that is the only feature I am interested in at the moment.

Makes sense! Thanks for the feedback
